### ISSUE TITLE
Salesforce connection create in constructor

### ISSUE THREAD

**Issue by AlexLombry** [davispeixoto/Laravel-5-Salesforce#15]
The Saleforce.php constructor create a connection to salesforce every time. 
When you try to launch some artisan command, the package always create a connection.

For instance, if i create a tail command for Laravel, in have a connection to salesforce even if i don't use salesforce at this time.

**Comment by davispeixoto** [comment]
@AlexLombry , just got what is happening. Thx for reporting this issue. I will make the changes until the next weekend.

**Comment by davispeixoto** [comment]
@AlexLombry , just made it. Can you try using version 2.0.3?

**Comment by AlexLombry** [comment]
I've just tried it and no it still connect. I think it's a design problem. Maybe not create the connection into the constructor but with a connect method maybe. Or make a singleton for the $this->app['salesforce']

**Comment by davispeixoto** [comment]
Can you confirm the version you installed, plz?

**Comment by AlexLombry** [comment]
Dependency resolution completed in 0.008 seconds
- Removing davispeixoto/laravel5-salesforce (2.0.2)
- Installing davispeixoto/laravel5-salesforce (2.0.3)

**Comment by AlexLombry** [comment]
If you make a var_dump("salesforce") in the SforceBaseClient.php on the login or createConnection method, you'll see that every command line you launch with Artisan call Salesforce.

I have 50 command called on my crontab and each of them call Salesforce login when they're launch but only 3 commands actually use Salesforce.

For example, assumed you have a command running every minutes on two servers.
It's 60 command \* 2 per hour, so that's create 120 login request to Salesforce per hour.

**Comment by davispeixoto** [comment]
@AlexLombry , I got your point, but I will require much more time in order to debug - I'm at work right now...

The most obvious points were checked
- The defer property
- Removed the boot method from the service provider
- Require the full manual setup (providers and aliases)

This leads me that I need to make a full debug into the Laravel booting process in order to check what is happening - and see if is there anything that can be really done.

By the way, there is already a bug report for this issue - that leaded me to change from version 1.x to 2.x.

**Comment by AlexLombry** [comment]
Thanks for your reply.

I may have a fix, use it as you wish but maybe it can help you.
I create two command, one without salesforce and one with it, and apparently it works.

I create a pull request, that way you can tell me if that little fix may help you ?

**Comment by davispeixoto** [comment]
@AlexLombry , thx for your contribution. I've merged your pull request and versioned it to 2.0.4
