### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by nicklee1990** [davispeixoto/Laravel-5-Salesforce#2]
Great library! Do you have any more examples for using the library e.g. creating a Lead?

**Comment by davispeixoto** [comment]
Hi @nicklee1990 . I didn't work for creating a documentation for this library yet. Mainly because it is just an adapter for the Salesforce Force.com PHP Toolkit.

They have [lots of documentation](https://developer.salesforce.com/page/PHP_Toolkit_20.0_Samples) that I think might help you out to understand how the Toolkit works. It's basically the same thing, but instead of instantiating the handler to SforceClient, you set up and use my library, inside Laravel scope.

Let mw know if you have any further questions.
