### ISSUE TITLE
Instantiate a class

### ISSUE THREAD

**Issue by gabohm** [davispeixoto/Laravel-5-Salesforce#26]
Hello, how can I instantiate a  new class? 
Like this, example: $sObject = new stdclass();

**Comment by davispeixoto** [comment]
I didn't get your question. From where is this example? What documentation are you reading?

**Comment by gabohm** [comment]
Is this documentation: https://developer.salesforce.com/page/PHP_Toolkit_20.0_Upsert_Sample_(Enterprise)
In the line 14, you can see: $sObject = new stdClass();
But I have this error:
Class 'App\Http\Controllers\stdclass' not found
how can I instantiate that new class with you library?
Thanks.

**Comment by davispeixoto** [comment]
OK, your problem is with namespacing.

stdClass (not stdclass) is part of PHP Core.

You have two options for making the example run properly:

1 - Using backslash:

$sObject = new \stdClass();

2 - Adding it with use;

// in the very top of your file

use \stdClass;

// then use

$sObject = new stdClass();

Otherwise, without specifying the namespace for this core class, it will lookup for a class named stdClass inside the same package.

This is valid for any core php objects (like DateTime...), and any code that really cares about OOP best practices (unfortunately, the salesforce documentation has most examples from PHP 5.2 age, when there were no namespacing).

**Comment by gabohm** [comment]
Perfect.
Thanks.
